function modelPath = build_gt_simulink_model()
%BUILD_GT_SIMULINK_MODEL Build the exploratory closed-loop Simulink model.

thisFile = mfilename('fullpath');
packageRoot = fileparts(fileparts(thisFile));
srcRoot = fullfile(packageRoot, 'src');
simRoot = fullfile(packageRoot, 'simulink');
if ~isfolder(simRoot)
    mkdir(simRoot);
end
addpath(srcRoot);
addpath(fullfile(packageRoot, 'scripts'));
init_gt_simulink_workspace();

model = 'GT_DualShaft_Dynamic_Exploratory';
modelPath = fullfile(simRoot, [model '.slx']);
if bdIsLoaded(model)
    close_system(model, 0);
end
new_system(model);
open_system(model);

set_param(model, ...
    'StopTime', 'GT_SIM.stop_time_s', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'ode4', ...
    'FixedStep', 'GT_SIM.fixed_step_s', ...
    'RelTol', '1e-6', ...
    'AbsTol', '1e-8', ...
    'InitFcn', 'init_gt_simulink_workspace;');

add_main_blocks(model);
connect_main_blocks(model);
save_system(model, modelPath);
end

function add_main_blocks(model)
interpretedFcn = library_block('Interpreted MATLAB Function');

add_block('simulink/Sources/Constant', [model '/N_PT_ref_rpm'], ...
    'Value', 'GT_SIM.N_PT_ref_rpm', 'Position', [40 40 140 70]);
add_block('simulink/Sources/Step', [model '/Pdc_Load_Step'], ...
    'Time', 'GT_SIM.load_step_time_s', ...
    'Before', 'GT_SIM.Pdc0_W', ...
    'After', 'GT_SIM.Pdc_step_W', ...
    'Position', [40 260 140 290]);
add_block('simulink/Continuous/Integrator', [model '/State_Integrator'], ...
    'InitialCondition', 'GT_SIM.x0', ...
    'Position', [520 160 560 220]);
add_block('simulink/Signal Routing/Mux', [model '/Plant_Input_Mux'], ...
    'Inputs', '3', 'Position', [300 180 325 250]);
add_block(interpretedFcn, ...
    [model '/Plant_Xdot'], 'MATLABFcn', 'gt_simulink_plant_xdot', ...
    'Position', [370 180 470 220]);
add_block(interpretedFcn, ...
    [model '/Plant_Output'], 'MATLABFcn', 'gt_simulink_plant_output', ...
    'Position', [370 260 470 300]);
add_block('simulink/Signal Routing/Demux', [model '/State_Demux'], ...
    'Outputs', '6', 'Position', [630 140 650 260]);
add_block('simulink/Math Operations/Gain', [model '/Radps_To_Rpm'], ...
    'Gain', '30/pi', 'Position', [710 170 790 200]);
add_block('simulink/Math Operations/Sum', [model '/Speed_Error_Rpm'], ...
    'Inputs', '+-', 'Position', [850 80 875 120]);
add_block('simulink/Math Operations/Gain', [model '/Normalize_Speed_Error'], ...
    'Gain', '1/GT_SIM.N_PT_ref_rpm', 'Position', [920 85 1040 115]);
add_block('simulink/Math Operations/Gain', [model '/Kp_Fuel'], ...
    'Gain', 'GT_SIM.Kp_fuel', 'Position', [1100 40 1180 70]);
add_block('simulink/Continuous/Integrator', ...
    [model '/Speed_Error_Integrator'], ...
    'InitialCondition', 'GT_SIM.int_e0', ...
    'Position', [1100 120 1140 160]);
add_block('simulink/Math Operations/Gain', [model '/Ki_Fuel'], ...
    'Gain', 'GT_SIM.Ki_fuel', 'Position', [1180 125 1260 155]);
add_block('simulink/Sources/Constant', [model '/Fuel_Base_Factor'], ...
    'Value', '1', 'Position', [1100 205 1180 235]);
add_block('simulink/Math Operations/Sum', [model '/Fuel_Demand_Factor'], ...
    'Inputs', '+++', 'Position', [1320 100 1345 165]);
add_block('simulink/Math Operations/Gain', [model '/Fuel_Flow_Scale'], ...
    'Gain', 'GT_SIM.Wf0_kgps', 'Position', [1390 115 1490 145]);
add_block('simulink/Discontinuities/Saturation', [model '/Fuel_Saturation'], ...
    'LowerLimit', 'GT_SIM.Wf_min_kgps', ...
    'UpperLimit', 'GT_SIM.Wf_max_kgps', ...
    'Position', [1530 115 1630 145]);
add_block('simulink/Sinks/To Workspace', [model '/x_state_log'], ...
    'VariableName', 'x_state', 'SaveFormat', 'Timeseries', ...
    'Position', [680 300 790 330]);
add_block('simulink/Sinks/To Workspace', [model '/plant_diag_log'], ...
    'VariableName', 'plant_diag', 'SaveFormat', 'Timeseries', ...
    'Position', [520 265 640 295]);
add_block('simulink/Sinks/To Workspace', [model '/fuel_cmd_log'], ...
    'VariableName', 'fuel_cmd', 'SaveFormat', 'Timeseries', ...
    'Position', [1680 115 1780 145]);
add_block('simulink/Sinks/To Workspace', [model '/pdc_load_log'], ...
    'VariableName', 'pdc_load', 'SaveFormat', 'Timeseries', ...
    'Position', [180 300 290 330]);
add_block('simulink/Sinks/To Workspace', [model '/speed_error_log'], ...
    'VariableName', 'speed_error_rel', 'SaveFormat', 'Timeseries', ...
    'Position', [1100 300 1230 330]);
end

function connect_main_blocks(model)
connect(model, 'State_Integrator/1', 'Plant_Input_Mux/1');
connect(model, 'Fuel_Saturation/1', 'Plant_Input_Mux/2');
connect(model, 'Pdc_Load_Step/1', 'Plant_Input_Mux/3');
connect(model, 'Plant_Input_Mux/1', 'Plant_Xdot/1');
connect(model, 'Plant_Xdot/1', 'State_Integrator/1');
connect(model, 'Plant_Input_Mux/1', 'Plant_Output/1');
connect(model, 'State_Integrator/1', 'State_Demux/1');
connect(model, 'State_Demux/2', 'Radps_To_Rpm/1');
connect(model, 'N_PT_ref_rpm/1', 'Speed_Error_Rpm/1');
connect(model, 'Radps_To_Rpm/1', 'Speed_Error_Rpm/2');
connect(model, 'Speed_Error_Rpm/1', 'Normalize_Speed_Error/1');
connect(model, 'Normalize_Speed_Error/1', 'Kp_Fuel/1');
connect(model, 'Normalize_Speed_Error/1', 'Speed_Error_Integrator/1');
connect(model, 'Kp_Fuel/1', 'Fuel_Demand_Factor/1');
connect(model, 'Speed_Error_Integrator/1', 'Ki_Fuel/1');
connect(model, 'Ki_Fuel/1', 'Fuel_Demand_Factor/2');
connect(model, 'Fuel_Base_Factor/1', 'Fuel_Demand_Factor/3');
connect(model, 'Fuel_Demand_Factor/1', 'Fuel_Flow_Scale/1');
connect(model, 'Fuel_Flow_Scale/1', 'Fuel_Saturation/1');
connect(model, 'State_Integrator/1', 'x_state_log/1');
connect(model, 'Plant_Output/1', 'plant_diag_log/1');
connect(model, 'Fuel_Saturation/1', 'fuel_cmd_log/1');
connect(model, 'Pdc_Load_Step/1', 'pdc_load_log/1');
connect(model, 'Normalize_Speed_Error/1', 'speed_error_log/1');
end

function connect(model, src, dst)
add_line(model, src, dst, 'autorouting', 'on');
end

function path = library_block(name)
load_system('simulink');
matches = find_system('simulink', 'LookUnderMasks', 'all', ...
    'FollowLinks', 'on', 'MatchFilter', @Simulink.match.allVariants, ...
    'Name', name);
if isempty(matches)
    error('GT:MissingSimulinkBlock', ...
        'Could not find Simulink library block named "%s".', name);
end
path = matches{1};
end
