function ic = build_gt_dynamic_initial_condition(GT)
%BUILD_GT_DYNAMIC_INITIAL_CONDITION Build dynamic state and input initials.

if nargin < 1 || isempty(GT)
    GT = build_gt_model_data();
end

stateNames = { ...
    'omega_GG_radps'; ...
    'omega_PT_radps'; ...
    'P3_Pa'; ...
    'P4_Pa'; ...
    'T3_K'; ...
    'Wf_act_kgps'};
stateUnits = { ...
    'rad/s'; ...
    'rad/s'; ...
    'Pa'; ...
    'Pa'; ...
    'K'; ...
    'kg/s'};
x0 = [ ...
    GT.init.omega_GG0_radps; ...
    GT.init.omega_PT0_radps; ...
    GT.init.P3_0_Pa; ...
    GT.init.P4_0_Pa; ...
    GT.init.T3_0_K; ...
    GT.init.Wf_act0_kgps];

u0 = struct( ...
    'Wf_cmd_kgps', GT.init.Wf_act0_kgps, ...
    'loadMode', 'dc_power', ...
    'P_dc_load_W', GT.req.P_dc_rated_W, ...
    'Tload_Nm', GT.init.Tload0_Nm);

registry = [ ...
    registry_entry('MATLAB/evaluate_gt_dynamics/x(1)', ...
    'state vector', stateNames{1}, x0(1), stateUnits{1}, ...
    'GT.init.omega_GG0_radps', ...
    'gas-generator rotor acceleration near zero'); ...
    registry_entry('MATLAB/evaluate_gt_dynamics/x(2)', ...
    'state vector', stateNames{2}, x0(2), stateUnits{2}, ...
    'GT.init.omega_PT0_radps', ...
    'power-turbine rotor acceleration near zero'); ...
    registry_entry('MATLAB/evaluate_gt_dynamics/x(3)', ...
    'state vector', stateNames{3}, x0(3), stateUnits{3}, ...
    'GT.init.P3_0_Pa', ...
    'P3 volume pressure derivative near zero'); ...
    registry_entry('MATLAB/evaluate_gt_dynamics/x(4)', ...
    'state vector', stateNames{4}, x0(4), stateUnits{4}, ...
    'GT.init.P4_0_Pa', ...
    'P4 volume pressure derivative near zero'); ...
    registry_entry('MATLAB/evaluate_gt_dynamics/x(5)', ...
    'state vector', stateNames{5}, x0(5), stateUnits{5}, ...
    'GT.init.T3_0_K', ...
    'combustor thermal derivative near zero'); ...
    registry_entry('MATLAB/evaluate_gt_dynamics/x(6)', ...
    'state vector', stateNames{6}, x0(6), stateUnits{6}, ...
    'GT.init.Wf_act0_kgps', ...
    'fuel actuator derivative near zero')];

ic = struct( ...
    'stateNames', {stateNames}, ...
    'stateUnits', {stateUnits}, ...
    'x0', x0, ...
    'u0', u0, ...
    'registry', registry);
end

function entry = registry_entry(path, blockType, state, initialValue, unit, ...
    source, check)
entry = struct( ...
    'path', path, ...
    'blockType', blockType, ...
    'state', state, ...
    'initialValue', initialValue, ...
    'unit', unit, ...
    'source', source, ...
    'check', check);
end
