function steady = evaluate_gt_steady_rated(GT, dataRoot)
%EVALUATE_GT_STEADY_RATED Evaluate the rated steady map-wrapper stage.
%
% This stage keeps the rated thermodynamic pressures from the design-point
% solution and replaces the compressor flow and turbine flow checks with the
% selected map wrappers. It is a rated-point closure check, not a full
% off-design matching solver.

if nargin < 1 || isempty(GT)
    GT = build_gt_model_data();
end
if nargin < 2 || isempty(dataRoot)
    dataRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end

audit = audit_gt_maps(dataRoot);

inputs = build_rated_inputs(GT);
compressor = evaluate_compressor(GT, audit, inputs);
combustor = evaluate_combustor(GT, inputs, compressor);
gasGeneratorTurbine = evaluate_gas_generator_turbine(GT, combustor);
powerTurbine = evaluate_power_turbine(GT, combustor, gasGeneratorTurbine);
residuals = build_residuals(GT, compressor, combustor, ...
    gasGeneratorTurbine, powerTurbine);
checks = build_checks(GT, audit, compressor, combustor, ...
    gasGeneratorTurbine, powerTurbine, residuals);

steady = struct( ...
    'stage', 'steady_map_rated', ...
    'inputs', inputs, ...
    'audit', audit, ...
    'compressor', compressor, ...
    'combustor', combustor, ...
    'gasGeneratorTurbine', gasGeneratorTurbine, ...
    'powerTurbine', powerTurbine, ...
    'residuals', residuals, ...
    'checks', checks);
end

function inputs = build_rated_inputs(GT)
inputs.P1_Pa = GT.design.state.P1_Pa;
inputs.T1_K = GT.design.state.T1_K;
inputs.pi_c = GT.design.pi_c;
inputs.N_GG_rel = GT.init.omega_GG0_radps / ...
    (pi*GT.req.N_GG0_rpm/30);
inputs.N_PT_rel = GT.init.omega_PT0_radps / ...
    (pi*GT.req.N_PT0_rpm/30);
inputs.Wf_kgps = GT.design.state.W_fuel_kgps;
inputs.Pload_shaft_W = GT.req.P_PT_shaft0_W;
inputs.Tload_Nm = GT.init.Tload0_Nm;
end

function compressor = evaluate_compressor(GT, audit, inputs)
assump = GT.assump;
scale = GT.mapScale.compressor;

pi_map = 1 + (inputs.pi_c - 1)/scale.local_s_pi;
map = evaluate_compressor_xpi_map(audit.compressor.files.xpi, pi_map, ...
    inputs.N_GG_rel);

W_air_kgps = map.W_map_rel * scale.local_s_W;
eta_c = scale.local_eta_map_dp * scale.local_s_eta;
T2s_K = inputs.T1_K * inputs.pi_c^((assump.gamma_air - 1)/ ...
    assump.gamma_air);
T2_K = inputs.T1_K + (T2s_K - inputs.T1_K)/eta_c;
P2_Pa = inputs.P1_Pa * inputs.pi_c;
P_comp_W = W_air_kgps * assump.cp_air_J_kgK * (T2_K - inputs.T1_K);

compressor = struct( ...
    'map_file', audit.compressor.files.xpi, ...
    'map_source', map.source, ...
    'pi_map', pi_map, ...
    'N_rel', inputs.N_GG_rel, ...
    'W_map_rel', map.W_map_rel, ...
    'W_air_kgps', W_air_kgps, ...
    'eta_c', eta_c, ...
    'efficiency_source', audit.compressor.efficiency_source, ...
    'P2_Pa', P2_Pa, ...
    'T2s_K', T2s_K, ...
    'T2_K', T2_K, ...
    'P_comp_W', P_comp_W, ...
    'map_valid', map.valid);
end

function combustor = evaluate_combustor(GT, inputs, compressor)
assump = GT.assump;
W_air = compressor.W_air_kgps;
W_fuel = inputs.Wf_kgps;
W_gas = W_air + W_fuel;
P3_Pa = assump.sigma_b * compressor.P2_Pa;
T3_K = (W_air*assump.cp_air_J_kgK*compressor.T2_K + ...
    assump.eta_b*W_fuel*assump.Hu_J_kg) / ...
    (W_gas*assump.cp_gas_J_kgK);

combustor = struct( ...
    'P3_Pa', P3_Pa, ...
    'T3_K', T3_K, ...
    'W_air_kgps', W_air, ...
    'W_fuel_kgps', W_fuel, ...
    'W_gas_kgps', W_gas, ...
    'fuel_air_ratio', W_fuel/W_air);
end

function turbine = evaluate_gas_generator_turbine(GT, combustor)
assump = GT.assump;
P4_Pa = GT.design.state.P4_Pa;
PR_TG = combustor.P3_Pa/P4_Pa;
W_turbine_kgps = stodola_flow(GT.mapScale.turbine.K_TG, ...
    combustor.P3_Pa, P4_Pa, combustor.T3_K);
T4s_K = combustor.T3_K * (1/PR_TG)^((assump.gamma_gas - 1)/ ...
    assump.gamma_gas);
T4_K = combustor.T3_K - assump.eta_tg*(combustor.T3_K - T4s_K);
P_TG_gas_W = W_turbine_kgps * assump.cp_gas_J_kgK * ...
    (combustor.T3_K - T4_K);
P_TG_shaft_W = assump.eta_mg * P_TG_gas_W;

turbine = struct( ...
    'P4_Pa', P4_Pa, ...
    'PR_TG', PR_TG, ...
    'W_turbine_kgps', W_turbine_kgps, ...
    'T4s_K', T4s_K, ...
    'T4_K', T4_K, ...
    'P_TG_gas_W', P_TG_gas_W, ...
    'P_TG_shaft_W', P_TG_shaft_W);
end

function turbine = evaluate_power_turbine(GT, ~, gasGeneratorTurbine)
assump = GT.assump;
P5_Pa = GT.design.state.P5_Pa;
T4_K = gasGeneratorTurbine.T4_K;
P4_Pa = gasGeneratorTurbine.P4_Pa;
PR_PT = P4_Pa/P5_Pa;
W_turbine_kgps = stodola_flow(GT.mapScale.turbine.K_PT, P4_Pa, ...
    P5_Pa, T4_K);
T5s_K = T4_K * (1/PR_PT)^((assump.gamma_gas - 1)/assump.gamma_gas);
T5_K = T4_K - assump.eta_pt*(T4_K - T5s_K);
P_PT_gas_W = W_turbine_kgps * assump.cp_gas_J_kgK * (T4_K - T5_K);
P_PT_shaft_W = assump.eta_mp * P_PT_gas_W;

turbine = struct( ...
    'P5_Pa', P5_Pa, ...
    'PR_PT', PR_PT, ...
    'W_turbine_kgps', W_turbine_kgps, ...
    'T5s_K', T5s_K, ...
    'T5_K', T5_K, ...
    'P_PT_gas_W', P_PT_gas_W, ...
    'P_PT_shaft_W', P_PT_shaft_W, ...
    'P_dc_W', P_PT_shaft_W*GT.req.eta_gen*GT.req.eta_rect);
end

function W_kgps = stodola_flow(K, Pin_Pa, Pout_Pa, Tin_K)
pressureRatioTerm = max(0, 1 - (Pout_Pa/Pin_Pa)^2);
W_kgps = K * Pin_Pa / sqrt(Tin_K) * sqrt(pressureRatioTerm);
end

function residuals = build_residuals(GT, compressor, combustor, ...
    gasGeneratorTurbine, powerTurbine)
design = GT.design;

residuals.compressor_flow_rel = (compressor.W_air_kgps - ...
    design.state.W_air_kgps)/design.state.W_air_kgps;
residuals.combustor_T3_K = combustor.T3_K - design.state.T3_K;
residuals.combustor_fuel_air_ratio = combustor.fuel_air_ratio - ...
    design.perf.fuel_air_ratio;
residuals.TG_flow_rel = (gasGeneratorTurbine.W_turbine_kgps - ...
    combustor.W_gas_kgps)/combustor.W_gas_kgps;
residuals.PT_flow_rel = (powerTurbine.W_turbine_kgps - ...
    combustor.W_gas_kgps)/combustor.W_gas_kgps;
residuals.GG_power_balance_rel = (gasGeneratorTurbine.P_TG_shaft_W - ...
    compressor.P_comp_W)/design.perf.P_comp_W;
residuals.PT_power_balance_rel = (powerTurbine.P_PT_shaft_W - ...
    GT.req.P_PT_shaft0_W)/GT.req.P_PT_shaft0_W;
residuals.DC_power_rel = (powerTurbine.P_dc_W - ...
    GT.req.P_dc_rated_W)/GT.req.P_dc_rated_W;
end

function checks = build_checks(GT, audit, compressor, combustor, ...
    gasGeneratorTurbine, powerTurbine, residuals)
checks.map_audit_ready = audit.summary.ready_for_steady_map_rated;
checks.compressor_map_valid = compressor.map_valid;
checks.temperature_order = compressor.T2_K > GT.design.state.T1_K && ...
    combustor.T3_K > gasGeneratorTurbine.T4_K && ...
    gasGeneratorTurbine.T4_K > powerTurbine.T5_K;
checks.pressure_order = compressor.P2_Pa > GT.design.state.P1_Pa && ...
    combustor.P3_Pa < compressor.P2_Pa && ...
    gasGeneratorTurbine.P4_Pa < combustor.P3_Pa && ...
    powerTurbine.P5_Pa < gasGeneratorTurbine.P4_Pa;
checks.flow_residuals_ok = max(abs([residuals.compressor_flow_rel, ...
    residuals.TG_flow_rel, residuals.PT_flow_rel])) < 1e-10;
checks.power_residuals_ok = max(abs([residuals.GG_power_balance_rel, ...
    residuals.PT_power_balance_rel, residuals.DC_power_rel])) < 1e-10;
checks.combustor_residual_ok = abs(residuals.combustor_T3_K) < 1e-8;
checks.all_passed = checks.map_audit_ready && checks.compressor_map_valid && ...
    checks.temperature_order && checks.pressure_order && ...
    checks.flow_residuals_ok && checks.power_residuals_ok && ...
    checks.combustor_residual_ok;
end
