function [xdot, y] = evaluate_gt_dynamics(~, x, u, GT, dataRoot)
%EVALUATE_GT_DYNAMICS Evaluate the reduced dual-shaft GT plant dynamics.
%
% State vector:
%   x(1) omega_GG_radps
%   x(2) omega_PT_radps
%   x(3) P3_Pa
%   x(4) P4_Pa
%   x(5) T3_K
%   x(6) Wf_act_kgps

if nargin < 4 || isempty(GT)
    GT = build_gt_model_data();
end
if nargin < 5 || isempty(dataRoot)
    dataRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end
if nargin < 2 || isempty(x) || nargin < 3 || isempty(u)
    ic = build_gt_dynamic_initial_condition(GT);
    if nargin < 2 || isempty(x)
        x = ic.x0;
    end
    if nargin < 3 || isempty(u)
        u = ic.u0;
    end
end

audit = cached_map_audit(dataRoot);
state = vector_to_state(x);
inputs = normalize_inputs(u, GT);

compressor = evaluate_dynamic_compressor(GT, audit, state);
combustor = evaluate_dynamic_combustor(GT, state, inputs, compressor);
gasGeneratorTurbine = evaluate_dynamic_gas_generator_turbine(GT, state, ...
    combustor);
powerTurbine = evaluate_dynamic_power_turbine(GT, state, ...
    gasGeneratorTurbine);
load = evaluate_dynamic_load(GT, state, inputs);
derivatives = build_derivatives(GT, state, inputs, compressor, combustor, ...
    gasGeneratorTurbine, powerTurbine, load);
residuals = build_dynamic_residuals(GT, inputs, compressor, combustor, ...
    gasGeneratorTurbine, powerTurbine, load);
checks = build_dynamic_checks(audit, compressor, residuals);

xdot = [ ...
    derivatives.omega_GG_radps2; ...
    derivatives.omega_PT_radps2; ...
    derivatives.P3_Paps; ...
    derivatives.P4_Paps; ...
    derivatives.T3_Kps; ...
    derivatives.Wf_act_kgps2];

y = struct( ...
    'stage', 'dynamic_plant', ...
    'state', state, ...
    'inputs', inputs, ...
    'audit', audit, ...
    'compressor', compressor, ...
    'combustor', combustor, ...
    'gasGeneratorTurbine', gasGeneratorTurbine, ...
    'powerTurbine', powerTurbine, ...
    'load', load, ...
    'derivatives', derivatives, ...
    'residuals', residuals, ...
    'checks', checks);
end

function state = vector_to_state(x)
state = struct( ...
    'omega_GG_radps', x(1), ...
    'omega_PT_radps', x(2), ...
    'P3_Pa', x(3), ...
    'P4_Pa', x(4), ...
    'T3_K', x(5), ...
    'Wf_act_kgps', x(6));
end

function audit = cached_map_audit(dataRoot)
persistent cachedRoot cachedAudit
if isempty(cachedRoot) || ~strcmp(cachedRoot, dataRoot)
    cachedRoot = dataRoot;
    cachedAudit = audit_gt_maps(dataRoot);
end
audit = cachedAudit;
end

function inputs = normalize_inputs(u, GT)
if isnumeric(u)
    inputs = struct( ...
        'Wf_cmd_kgps', u(1), ...
        'loadMode', 'dc_power', ...
        'P_dc_load_W', u(2), ...
        'Tload_Nm', GT.init.Tload0_Nm);
    if numel(u) >= 3
        inputs.Tload_Nm = u(3);
    end
    return;
end

inputs = u;
if ~isfield(inputs, 'Wf_cmd_kgps')
    inputs.Wf_cmd_kgps = GT.init.Wf_act0_kgps;
end
if ~isfield(inputs, 'loadMode')
    inputs.loadMode = 'dc_power';
end
if ~isfield(inputs, 'P_dc_load_W')
    inputs.P_dc_load_W = GT.req.P_dc_rated_W;
end
if ~isfield(inputs, 'Tload_Nm')
    inputs.Tload_Nm = GT.init.Tload0_Nm;
end
end

function compressor = evaluate_dynamic_compressor(GT, audit, state)
assump = GT.assump;
scale = GT.mapScale.compressor;
omega_GG0 = pi*GT.req.N_GG0_rpm/30;

P1_Pa = GT.design.state.P1_Pa;
T1_K = GT.design.state.T1_K;
P2_Pa = state.P3_Pa/assump.sigma_b;
pi_c_raw = P2_Pa/P1_Pa;
pi_c = max(pi_c_raw, 1.001);
N_rel = state.omega_GG_radps/omega_GG0;
pi_map = 1 + (pi_c - 1)/scale.local_s_pi;
map = evaluate_compressor_xpi_map(audit.compressor.files.xpi, pi_map, ...
    N_rel);

W_air_kgps = max(0, map.W_map_rel * scale.local_s_W);
eta_c = scale.local_eta_map_dp * scale.local_s_eta;
T2s_K = T1_K * pi_c^((assump.gamma_air - 1)/assump.gamma_air);
T2_K = T1_K + (T2s_K - T1_K)/eta_c;
P_comp_W = W_air_kgps * assump.cp_air_J_kgK * (T2_K - T1_K);

compressor = struct( ...
    'P1_Pa', P1_Pa, ...
    'T1_K', T1_K, ...
    'P2_Pa', P2_Pa, ...
    'pi_c', pi_c, ...
    'pi_c_raw', pi_c_raw, ...
    'pi_map', pi_map, ...
    'N_rel', N_rel, ...
    'W_map_rel', map.W_map_rel, ...
    'W_air_kgps', W_air_kgps, ...
    'eta_c', eta_c, ...
    'T2s_K', T2s_K, ...
    'T2_K', T2_K, ...
    'P_comp_W', P_comp_W, ...
    'map_source', map.source, ...
    'map_valid', map.valid && pi_c_raw > 1);
end

function combustor = evaluate_dynamic_combustor(GT, state, inputs, ...
    compressor)
assump = GT.assump;
W_air = compressor.W_air_kgps;
W_fuel = max(0, state.Wf_act_kgps);
W_gas = W_air + W_fuel;
T3_eq_K = (W_air*assump.cp_air_J_kgK*compressor.T2_K + ...
    assump.eta_b*W_fuel*assump.Hu_J_kg) / ...
    (W_gas*assump.cp_gas_J_kgK);

combustor = struct( ...
    'P3_Pa', state.P3_Pa, ...
    'T3_K', state.T3_K, ...
    'T3_eq_K', T3_eq_K, ...
    'W_air_kgps', W_air, ...
    'W_fuel_kgps', W_fuel, ...
    'W_gas_kgps', W_gas, ...
    'fuel_air_ratio', W_fuel/W_air, ...
    'fuel_cmd_kgps', inputs.Wf_cmd_kgps);
end

function turbine = evaluate_dynamic_gas_generator_turbine(GT, state, ...
    combustor)
assump = GT.assump;
PR_TG_raw = state.P3_Pa/state.P4_Pa;
PR_TG = max(PR_TG_raw, 1.001);
W_turbine_kgps = stodola_flow(GT.mapScale.turbine.K_TG, state.P3_Pa, ...
    state.P4_Pa, state.T3_K);
T4s_K = state.T3_K * (1/PR_TG)^((assump.gamma_gas - 1)/ ...
    assump.gamma_gas);
T4_K = state.T3_K - assump.eta_tg*(state.T3_K - T4s_K);
P_TG_gas_W = W_turbine_kgps * assump.cp_gas_J_kgK * ...
    (state.T3_K - T4_K);
P_TG_shaft_W = assump.eta_mg * P_TG_gas_W;

turbine = struct( ...
    'P4_Pa', state.P4_Pa, ...
    'PR_TG', PR_TG, ...
    'PR_TG_raw', PR_TG_raw, ...
    'W_turbine_kgps', W_turbine_kgps, ...
    'T4s_K', T4s_K, ...
    'T4_K', T4_K, ...
    'P_TG_gas_W', P_TG_gas_W, ...
    'P_TG_shaft_W', P_TG_shaft_W, ...
    'map_valid', PR_TG_raw > 1 && combustor.W_gas_kgps > 0);
end

function turbine = evaluate_dynamic_power_turbine(GT, state, ...
    gasGeneratorTurbine)
assump = GT.assump;
P5_Pa = GT.design.state.P5_Pa;
PR_PT_raw = state.P4_Pa/P5_Pa;
PR_PT = max(PR_PT_raw, 1.001);
T4_K = gasGeneratorTurbine.T4_K;
W_turbine_kgps = stodola_flow(GT.mapScale.turbine.K_PT, state.P4_Pa, ...
    P5_Pa, T4_K);
T5s_K = T4_K * (1/PR_PT)^((assump.gamma_gas - 1)/assump.gamma_gas);
T5_K = T4_K - assump.eta_pt*(T4_K - T5s_K);
P_PT_gas_W = W_turbine_kgps * assump.cp_gas_J_kgK * (T4_K - T5_K);
P_PT_shaft_W = assump.eta_mp * P_PT_gas_W;

turbine = struct( ...
    'P5_Pa', P5_Pa, ...
    'PR_PT', PR_PT, ...
    'PR_PT_raw', PR_PT_raw, ...
    'W_turbine_kgps', W_turbine_kgps, ...
    'T5s_K', T5s_K, ...
    'T5_K', T5_K, ...
    'P_PT_gas_W', P_PT_gas_W, ...
    'P_PT_shaft_W', P_PT_shaft_W, ...
    'map_valid', PR_PT_raw > 1);
end

function load = evaluate_dynamic_load(GT, state, inputs)
eta_chain = GT.req.eta_gen * GT.req.eta_rect;
omega_safe = max(abs(state.omega_PT_radps), GT.dyn.omega_PT_min_radps);

if strcmp(inputs.loadMode, 'torque')
    Tload_Nm = inputs.Tload_Nm;
    Pload_shaft_W = Tload_Nm * omega_safe;
    P_dc_W = Pload_shaft_W * eta_chain;
else
    P_dc_W = inputs.P_dc_load_W;
    Pload_shaft_W = P_dc_W / eta_chain;
    Tload_Nm = Pload_shaft_W / omega_safe;
end

load = struct( ...
    'mode', inputs.loadMode, ...
    'P_dc_W', P_dc_W, ...
    'Pload_shaft_W', Pload_shaft_W, ...
    'Tload_Nm', Tload_Nm);
end

function derivatives = build_derivatives(GT, state, inputs, compressor, ...
    combustor, gasGeneratorTurbine, powerTurbine, load)
omega_GG_safe = max(abs(state.omega_GG_radps), GT.dyn.omega_GG_min_radps);
omega_PT_safe = max(abs(state.omega_PT_radps), GT.dyn.omega_PT_min_radps);

derivatives = struct( ...
    'omega_GG_radps2', (gasGeneratorTurbine.P_TG_shaft_W - ...
    compressor.P_comp_W)/(GT.dyn.J_GG_kgm2*omega_GG_safe), ...
    'omega_PT_radps2', (powerTurbine.P_PT_shaft_W - ...
    load.Pload_shaft_W)/(GT.dyn.J_PT_kgm2*omega_PT_safe), ...
    'P3_Paps', GT.assump.R_gas_J_kgK*state.T3_K * ...
    (combustor.W_gas_kgps - gasGeneratorTurbine.W_turbine_kgps) / ...
    GT.dyn.V3_m3, ...
    'P4_Paps', GT.assump.R_gas_J_kgK*gasGeneratorTurbine.T4_K * ...
    (gasGeneratorTurbine.W_turbine_kgps - ...
    powerTurbine.W_turbine_kgps) / GT.dyn.V4_m3, ...
    'T3_Kps', (combustor.T3_eq_K - state.T3_K)/GT.dyn.tau_T3_s, ...
    'Wf_act_kgps2', (inputs.Wf_cmd_kgps - state.Wf_act_kgps)/ ...
    GT.dyn.tau_f_s);
end

function residuals = build_dynamic_residuals(GT, inputs, compressor, ...
    combustor, gasGeneratorTurbine, powerTurbine, load)
Wgas = max(combustor.W_gas_kgps, eps);

residuals.compressor_flow_rel = (compressor.W_air_kgps - ...
    GT.design.state.W_air_kgps)/GT.design.state.W_air_kgps;
residuals.P3_flow_rel = (combustor.W_gas_kgps - ...
    gasGeneratorTurbine.W_turbine_kgps)/Wgas;
residuals.P4_flow_rel = (gasGeneratorTurbine.W_turbine_kgps - ...
    powerTurbine.W_turbine_kgps)/Wgas;
residuals.GG_power_balance_rel = (gasGeneratorTurbine.P_TG_shaft_W - ...
    compressor.P_comp_W)/GT.design.perf.P_comp_W;
residuals.PT_power_balance_rel = (powerTurbine.P_PT_shaft_W - ...
    load.Pload_shaft_W)/GT.req.P_PT_shaft0_W;
residuals.T3_eq_rel = (combustor.T3_eq_K - combustor.T3_K) / ...
    GT.design.state.T3_K;
residuals.fuel_actuator_rel = (inputs.Wf_cmd_kgps - ...
    combustor.W_fuel_kgps)/GT.design.state.W_fuel_kgps;
residuals.load_dc_rel = (load.P_dc_W - GT.req.P_dc_rated_W)/ ...
    GT.req.P_dc_rated_W;
end

function checks = build_dynamic_checks(audit, compressor, residuals)
checks.map_audit_ready = audit.summary.ready_for_steady_map_rated;
checks.compressor_map_valid = compressor.map_valid;
checks.flow_residuals_ok = max(abs([residuals.P3_flow_rel, ...
    residuals.P4_flow_rel])) < 1e-10;
checks.power_residuals_ok = max(abs([residuals.GG_power_balance_rel, ...
    residuals.PT_power_balance_rel])) < 1e-10;
checks.thermal_residual_ok = abs(residuals.T3_eq_rel) < 1e-10;
checks.fuel_residual_ok = abs(residuals.fuel_actuator_rel) < 1e-10;
checks.all_passed = checks.map_audit_ready && checks.compressor_map_valid && ...
    checks.flow_residuals_ok && checks.power_residuals_ok && ...
    checks.thermal_residual_ok && checks.fuel_residual_ok;
end

function W_kgps = stodola_flow(K, Pin_Pa, Pout_Pa, Tin_K)
pressureRatioTerm = max(0, 1 - (Pout_Pa/Pin_Pa)^2);
W_kgps = K * Pin_Pa / sqrt(Tin_K) * sqrt(pressureRatioTerm);
end
