function diag = gt_simulink_plant_output(inputVector)
%GT_SIMULINK_PLANT_OUTPUT Simulink wrapper for numeric plant diagnostics.

GT_SIM = evalin('base', 'GT_SIM');
x = inputVector(1:6);
u = struct( ...
    'Wf_cmd_kgps', inputVector(7), ...
    'loadMode', 'dc_power', ...
    'P_dc_load_W', inputVector(8), ...
    'Tload_Nm', GT_SIM.GT.init.Tload0_Nm);

[~, y] = evaluate_gt_dynamics(0, x, u, GT_SIM.GT, GT_SIM.dataRoot);

diag = [ ...
    y.state.omega_GG_radps*30/pi; ...
    y.state.omega_PT_radps*30/pi; ...
    y.state.P3_Pa/1e6; ...
    y.state.P4_Pa/1e6; ...
    y.state.T3_K; ...
    y.state.Wf_act_kgps; ...
    y.inputs.Wf_cmd_kgps; ...
    y.load.P_dc_W; ...
    y.powerTurbine.P_PT_shaft_W/1e6; ...
    double(y.compressor.map_valid); ...
    double(y.checks.all_passed); ...
    y.residuals.PT_power_balance_rel; ...
    y.load.Tload_Nm/1e3; ...
    y.compressor.pi_c];
end
